export const staticPrimaryColor = '#E9CC1E'; // Yellow
export const staticPrimaryDarkenColor = '#D4B215'; // Slightly darker yellow

export const themes = {
  light: {
    dark: false,
    colors: {
      'primary': staticPrimaryColor,
      'on-primary': '#000', // Text on primary color
      'primary-darken-1': staticPrimaryDarkenColor,
      'secondary': '#FFE066', // Light yellow secondary
      'secondary-darken-1': '#FFD54F',
      'on-secondary': '#000',
      'success': '#F3D233', // Yellowish-green for success
      'success-darken-1': '#E0BE29',
      'on-success': '#000',
      'info': '#FFEB5E', // Light yellowish info
      'info-darken-1': '#E8D852',
      'on-info': '#000',
      'warning': '#F7C846', // Orange-yellow for warning
      'warning-darken-1': '#E0B540',
      'on-warning': '#000',
      'error': '#FF6F6F', // Light red for error
      'error-darken-1': '#E66060',
      'on-error': '#000',
      'background': '#FFFFFF',
      'on-background': '#000000',
      'surface': '#FFFBE5', // Light yellowish background
      'on-surface': '#000000',
      'grey-50': '#FFFDF0',
      'grey-100': '#FFF8E1',
      'grey-200': '#FFF3C9',
      'grey-300': '#FFE8A1',
      'grey-400': '#FFDB7B',
      'grey-500': '#FFD157',
      'grey-600': '#FFBF33',
      'grey-700': '#E8AB2A',
      'grey-800': '#D59A22',
      'grey-900': '#C0841C',
      'perfect-scrollbar-thumb': '#E9DFAE',
      'skin-bordered-background': '#FFFFFF',
      'skin-bordered-surface': '#FFFFFF',
      'expansion-panel-text-custom-bg': '#FFFBE5',
      'track-bg': '#FFF3C9',
      'chat-bg': '#FFFAE8',
    },
    variables: {
      'code-color': '#FFD600',
      'overlay-scrim-background': '#E9CC1E',
      'tooltip-background': '#FFF8E1',
      'overlay-scrim-opacity': 0.5,
      'hover-opacity': 0.04,
      'focus-opacity': 0.1,
      'selected-opacity': 0.08,
      'activated-opacity': 0.16,
      'pressed-opacity': 0.14,
      'dragged-opacity': 0.1,
      'disabled-opacity': 0.4,
      'border-color': '#E0BE29',
      'border-opacity': 0.12,
      'table-header-color': '#FFF8E1',
      'high-emphasis-opacity': 0.9,
      'medium-emphasis-opacity': 0.7,
      'shadow-key-umbra-color': '#E9CC1E',
      'shadow-xs-opacity': '0.16',
      'shadow-sm-opacity': '0.18',
      'shadow-md-opacity': '0.20',
      'shadow-lg-opacity': '0.22',
      'shadow-xl-opacity': '0.24',
    },
  },
  dark: {
    dark: true,
    colors: {
      'primary': staticPrimaryColor,
      'on-primary': '#000',
      'primary-darken-1': staticPrimaryDarkenColor,
      'secondary': '#FFD54F', // Dark yellow for secondary
      'secondary-darken-1': '#E8C041',
      'on-secondary': '#000',
      'success': '#F3D233',
      'success-darken-1': '#E0BE29',
      'on-success': '#000',
      'info': '#F4C536', // Yellowish info
      'info-darken-1': '#D9B02E',
      'on-info': '#000',
      'warning': '#F7C846',
      'warning-darken-1': '#E0B540',
      'on-warning': '#000',
      'error': '#FF6F6F',
      'error-darken-1': '#E66060',
      'on-error': '#000',
      'background': '#121212', // Dark background
      'on-background': '#E9CC1E',
      'surface': '#1F1F1F', // Dark surface
      'on-surface': '#E9CC1E',
      'grey-50': '#1A1A1A',
      'grey-100': '#242424',
      'grey-200': '#333333',
      'grey-300': '#3E3E3E',
      'grey-400': '#575757',
      'grey-500': '#717171',
      'grey-600': '#8A8A8A',
      'grey-700': '#A3A3A3',
      'grey-800': '#BEBEBE',
      'grey-900': '#E0E0E0',
      'perfect-scrollbar-thumb': '#575757',
      'skin-bordered-background': '#1F1F1F',
      'skin-bordered-surface': '#1F1F1F',
      'expansion-panel-text-custom-bg': '#1A1A1A',
      'track-bg': '#242424',
      'chat-bg': '#1C1C1C',
    },
    variables: {
      'code-color': '#FFD600',
      'overlay-scrim-background': '#1F1F1F',
      'tooltip-background': '#2A2A2A',
      'overlay-scrim-opacity': 0.5,
      'hover-opacity': 0.04,
      'focus-opacity': 0.1,
      'selected-opacity': 0.08,
      'activated-opacity': 0.16,
      'pressed-opacity': 0.14,
      'dragged-opacity': 0.1,
      'disabled-opacity': 0.4,
      'border-color': '#FFD600',
      'border-opacity': 0.12,
      'table-header-color': '#1A1A1A',
      'high-emphasis-opacity': 0.9,
      'medium-emphasis-opacity': 0.7,
      'shadow-key-umbra-color': '#131313',
      'shadow-xs-opacity': '0.20',
      'shadow-sm-opacity': '0.22',
      'shadow-md-opacity': '0.24',
      'shadow-lg-opacity': '0.26',
      'shadow-xl-opacity': '0.28',
    },
  },
};

export default themes;
